# Kapitel 7

In [1]:
def Stellenwerte(n:int,b:int)->list[int]: 
    # Entwickelt n in Basis b
    r=[]
    while n>0:
        r=r+[n%b]
        n=n//b
    return r
print(Stellenwerte(7109,10))
print(Stellenwerte(7109,2))
def ZahlAusStellen(s:list[int],b:int)->int:
    return sum([s[k]*b**k for k in range(len(s))])
print(ZahlAusStellen([9,0,1,7],10))


[9, 0, 1, 7]
[1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1]
7109


In [2]:
def plus(a:list,b:list,basis=10)->list: # Addition
    while len(a)<len(b):
        a=a+[0]
    while len(a)>len(b):
        b=b+[0]
    res=[]; übertrag=0
    for i in range(len(a)):
        s=a[i]+b[i]+übertrag
        res=res+[s%basis]
        übertrag=s//basis
    if übertrag>0:
        res=res+[übertrag]
    return res
a=Stellenwerte(7378,10); b=Stellenwerte(9876,10)
print(ZahlAusStellen(plus(a,b),10),"=",7378+9876)

def multZiffer(a:list,z:int,basis=10)->list: # Multipliziert mit einer Ziffer
    übertrag=0
    res=[]
    for k in range(len(a)):
        s=z*a[k]+übertrag
        res.append(s%basis)
        übertrag=s//basis
    if übertrag>0:
        res.append(übertrag)
    return res
print("321*4=",321*4,multZiffer([1,2,3],4))
def mult(a:list,b:list,basis=10)->list:
    res=[]
    for i in range(len(b)):
        res=plus(res,[0]*i+multZiffer(a,b[i],basis))
    return res
print(ZahlAusStellen(mult(a,b),10),"=",7378*9876)
print(mult(Stellenwerte(5,2),Stellenwerte(12,2),2))    

17254 = 17254
321*4= 1284 [4, 8, 2, 1]
72865128 = 72865128
[0, 0, 1, 1, 1, 1]


In [3]:
# Brüche als Listen wie [1,2] für 1/2
def ggT(a:int,b:int)->int: # Variante mit Mehrfachzuweisungen
    while b !=0:
        [q, r] = [a//b, a%b] 
        [a,b]=[b,r]
    return a
def gekürzt(B:list[int])->list[int]:
    z=B[0]; n=B[1]
    if n<0:
        z=-z; n=-n
    g=ggT(abs(z),n)
    z=z//g; n=n//g
    return [z,n]
a=[5,6]; b=[12,-18]; print(b,"=",gekürzt(b))
def Badd(a:list[int],b:list[int])->list[int]:
    return gekürzt([a[0]*b[1]+a[1]*b[0],a[1]*b[1]])
print(a,"+",b,"=",Badd(a,b))
def Bsub(a:list[int],b:list[int])->list[int]:
    return gekürzt([a[0]*b[1]-a[1]*b[0],a[1]*b[1]])
print(a,"-",b,"=",Bsub(a,b))
def Bmul(a:list[int],b:list[int])->list[int]:
    return gekürzt([a[0]*b[0],a[1]*b[1]])
print(a,"*",b,"=",Bmul(a,b))
def Bdiv(a:list[int],b:list[int])->list[int]:
    return gekürzt([a[0]*b[1],a[1]*b[0]])
print(a,"/",b,"=",Bdiv(a,b))

[12, -18] = [-2, 3]
[5, 6] + [12, -18] = [1, 6]
[5, 6] - [12, -18] = [3, 2]
[5, 6] * [12, -18] = [-5, 9]
[5, 6] / [12, -18] = [-5, 4]


In [4]:
# Komplexe Zahlen als Listen wie [1,2] für 1+2i
import math
a=[5,6]; b=[12,-18];
def CBetrag(z:list[float])->float:
    return math.sqrt(z[0]**2+z[1]**2)
def CKonjug(z:list[float])->list[float]:
    return [z[0],-z[1]]
def Cadd(a:list[float],b:list[float])->list[float]:
    return [a[0]+b[0],a[1]+b[1]]
def Csub(a:list[float],b:list[float])->list[float]:
    return [a[0]-b[0],a[1]-b[1]]
print(a,"+",b,"=",Cadd(a,b))
print(a,"-",b,"=",Csub(a,b))
def Cmul(a:list[float],b:list[float])->list[float]:
    return [a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]]
print(a,"*",b,"=",Cmul(a,b))
def Cdiv(a:list[float],b:list[float])->list[float]:
    return Cmul(a,Cinv(b))
def Cinv(a:list[float])->list[float]:
    n=a[0]**2+a[1]**2
    return [a[0]/n,-a[1]/n]
print(a,"/",b,"=",Cdiv(a,b))

[5, 6] + [12, -18] = [17, -12]
[5, 6] - [12, -18] = [-7, 24]
[5, 6] * [12, -18] = [168, -18]
[5, 6] / [12, -18] = [-0.10256410256410259, 0.34615384615384615]


In [5]:
Cinv([2,3])

[0.15384615384615385, -0.23076923076923078]

In [6]:
from fractions import Fraction
a=Fraction(5,6); b=Fraction(12,-18)
print("a=",a,"b=",b,"a+b=",a+b,"a-b=",a-b,"a*b=",a*b,"a/b=",a/b)
print(a,"als Fließpunktzahl",float(a))

a= 5/6 b= -2/3 a+b= 1/6 a-b= 3/2 a*b= -5/9 a/b= -5/4
5/6 als Fließpunktzahl 0.8333333333333334


In [7]:
a=complex(5,6); b=complex(12,-18)
print(type(a))
print(a,"=",a.real,"+i*",a.imag)
print("a=",a,"b=",b,"a+b=",a+b,"a-b=",a-b,"a*b=",a*b,"a/b=",a/b)

<class 'complex'>
(5+6j) = 5.0 +i* 6.0
a= (5+6j) b= (12-18j) a+b= (17-12j) a-b= (-7+24j) a*b= (168-18j) a/b= (-0.10256410256410257+0.34615384615384615j)


In [8]:
import sys
print(sys.float_info.max)   # größte positive float-Zahl
print(sys.float_info.min)   # kleinste positive float-Zahl

1.7976931348623157e+308
2.2250738585072014e-308


In [9]:
z=1.0
for j in range(20):
    z=z*10**20
    print(z)

1e+20
1e+40
1e+60
1e+80
1e+100
1e+120
1e+140
1e+160
1e+180
1e+200
1e+220
1e+240
1e+260
1e+280
1e+300
inf
inf
inf
inf
inf


In [10]:
print(1 / float('inf')) 
print(float('inf')+1) 

0.0
inf


In [11]:
x=0.2
for i in range(20):
    x=11*x-2
    print(x)

0.20000000000000018
0.20000000000000195
0.2000000000000215
0.20000000000023643
0.20000000000260076
0.2000000000286084
0.20000000031469245
0.20000000346161695
0.20000003807778644
0.20000041885565079
0.20000460741215864
0.20005068153374506
0.20055749687119562
0.2061324655831518
0.2674571214146697
0.9420283355613668
8.362311691175034
89.98542860292537
987.839714632179
10864.23686095397


In [12]:
# Archimedes
import math
n=6; s=1;
for j in range(30):
    n=2*n; 
    #s=math.sqrt((1-math.sqrt(1-(s/2)**2))**2+(s/2)**2) 
    s=math.sqrt(2-2*math.sqrt(1-(s/2)**2))
    p=n/2*s
    print(n,":",p,math.pi-p)
    

12 : 3.1058285412302498 0.035764112359543354
24 : 3.132628613281237 0.008964040308556243
48 : 3.139350203046872 0.0022424505429210484
96 : 3.14103195089053 0.0005607026992633379
192 : 3.1414524722853443 0.0001401813044488165
384 : 3.141557607911622 3.504567817103066e-05
768 : 3.141583892148936 8.76144085726338e-06
1536 : 3.1415904632367617 2.1903530313949204e-06
3072 : 3.1415921060430483 5.475467448334825e-07
6144 : 3.1415925165881546 1.3700163847829572e-07
12288 : 3.1415926186407894 3.4949003691053804e-08
24576 : 3.1415926453212157 8.268577378345299e-09
49152 : 3.1415926453212157 8.268577378345299e-09
98304 : 3.1415926453212157 8.268577378345299e-09
196608 : 3.1415926453212157 8.268577378345299e-09
393216 : 3.141593669849427 -1.0162596337792706e-06
786432 : 3.1415923038117377 3.497780554084784e-07
1572864 : 3.1416086962248038 -1.6042635010649064e-05
3145728 : 3.1415868396550413 5.813934751852656e-06
6291456 : 3.1416742650217575 -8.161143196439014e-05
12582912 : 3.1416742650217575 -8.1

In [13]:
# Polynome
from fractions import Fraction
p=[5,3,2]; q=[1,0,0,7]
def Pwert(p:list,x): # Wert der Polynomfunktion
    return sum([p[k]*x**k for k in range(len(p))])
[Pwert(p,1),Pwert(q,0)]

[10, 1]

In [14]:
def Pstr(p:list,var="x")->str:
    if p==[]: return "0"
    s=""
    for i in range(len(p)-1,-1,-1):
        if p[i]==0:
            continue
        if i==0:
            s=s+"+"+str(p[i])
        if i==1:
            s=s+"+"+str(p[i])+"*"+var
        if i>1:
            if i==len(p)-1:
                s=str(p[i])+"*"+var+"^"+str(i)
            else: 
                s=s+"+"+str(p[i])+"*"+var+"^"+str(i)
    return s
print("Wert von ",Pstr(p),"bei x=2",Pwert(p,2))

Wert von  2*x^2+3*x+5 bei x=2 19


In [15]:
def Pstandard(p:list)->list:
    while len(p)>0 and p[-1]==0: 
        p=p[0:len(p)-1]
    return(p)
def Pdeg(p:list)->int: # Grad
    return len(Pstandard(p))-1
def Padd(a:list,b:list)->list: # Addition
    while len(a)<len(b):
        a=a+[0] 
    while len(b)<len(a):
        b=b+[0]         
    return Pstandard([a[i]+b[i] for i in range(len(a))])
print(Pstr(p)+" + "+Pstr(q)+" = "+Pstr(Padd(p,q)))
def Psub(a:list,b:list)->list: 
    while len(a)<len(b): # Subtraktion
        a=a+[0] 
    while len(b)<len(a):
        b=b+[0]         
    return Pstandard([a[i]-b[i] for i in range(len(a))])
def PSmul(p:list, s)->list: # Multiplikation mit Zahl s
    return Pstandard([s*x for x in p]) 
def Pmul(a:list,b:list)->list:
    res=[0]*(1+(len(a)-1)+(len(b)-1)) 
    # Ergebnis wird Polynom vom Grad(a)+Grad(b)
    for i in range(len(a)):
        for j in range(len(b)):
            res[i+j]+=a[i]*b[j]
    return Pstandard(res)
print(Pstr(p)+" * "+Pstr(q)+" = "+Pstr(Pmul(p,q)))


2*x^2+3*x+5 + 7*x^3+1 = 7*x^3+2*x^2+3*x+6
2*x^2+3*x+5 * 7*x^3+1 = 14*x^5+21*x^4+35*x^3+2*x^2+3*x+5


In [16]:
def Pdiv(dividend:list, divisor:list)->list[list]:
    def quot(a,b): # Division, ggf als Bruch
        if type(a)==int and type(b)==int: 
            if a%b==0: 
                return a//b
            else:
                return Fraction(a,b)
        return a/b
    # Kopien anlegen und führende Nullen entfernen
    r=Pstandard(dividend[:]); d=Pstandard(divisor[:])
    if len(d)==0 or (len(d) == 1 and d[0] == 0):
        raise ZeroDivisionError("Division durch das Nullpolynom")
    m = len(r)-1 # Grad dividend
    n = len(d)-1 # Grad divisor
    if m<n: return [[0],r]
    q=[0]*(m-n+1) # Liste passender länge für den Quotienten
    while len(r)-1>=n:
        coef=quot(r[-1],d[-1])
        deg =(len(r)-1)-n # Grad des Ergebnisses
        q[deg] = coef
        # Subtrahiere coef*x^deg*d von r
        for i in range(len(d)): 
            r[i+deg]=r[i+deg]-coef*d[i]
        r=Pstandard(r); 
    q=Pstandard(q)
    return [q,r]

p=[1,2,1]; q=[1,1]
print(Pstr(p)+" / "+Pstr(q)+" = "+Pstr(Pdiv(p,q)[0])+" Rest "+Pstr(Pdiv(p,q)[1]) )
p=[0,0,0,0,-1,4]; q=[1,-1,2]
print(Pstr(p)+" / "+Pstr(q)+" = "+Pstr(Pdiv(p,q)[0])+" Rest "+Pstr(Pdiv(p,q)[1]) )


1*x^2+2*x+1 / +1*x+1 = +1*x+1 Rest 0
4*x^5+-1*x^4 / 2*x^2+-1*x+1 = 2*x^3+1/2*x^2+-3/4*x+-5/8 Rest +1/8*x+5/8


In [17]:
def PggT(a:list[int], b:list[int])->list[int]: # GGT ganzzahliger Polynome 
    a = Pstandard(a); b = Pstandard(b)
    while (b != [0] and b!=[]):
        [q, r] = Pdiv(a, b) 
        [a,b]=[b,r]
    # Jetzt ist a ggT, aber Koeffizienten evtl nicht ganzzahlig
    a = Pstandard(a);
    for i in range(len(a)):
        if type(a[i])==Fraction:
            a=PSmul(a,a[i].denominator)
    # gemeinsamen Faktor entfernen:
    if len(a)>1:
        g=ggT(a[0],a[1])
        for j in range(2,len(a)):
            g=ggT(g,a[j])
            
        a=[x//g for x in a]
    return a
p=[9,-1,12,-1,3]; q=[-9,-8,-2,6,-1,3]
print("ggT("+Pstr(p)+" , "+Pstr(q)+") = "+Pstr(PggT(p,q))) 
p = [1,0,-3,2]; q = [1,0,-1]
print("ggT("+Pstr(p)+" , "+Pstr(q)+") = "+Pstr(PggT(p,q))) 


ggT(3*x^4+-1*x^3+12*x^2+-1*x+9 , 3*x^5+-1*x^4+6*x^3+-2*x^2+-8*x+-9) = 3*x^2+-1*x+9
ggT(2*x^3+-3*x^2+1 , -1*x^2+1) = +1*x+-1


In [18]:
def InterPol(xs, ys): # Interpolationspolynom nach Lagrange durch xs,ys (Listen von Zahlen)
    n=len(xs)
    coeffs= [0 for i in range(n)] 
    for j in range(n):
        xj, yj = xs[j], ys[j]
        # Lagrange-Basispolynom Lj(x)
        Lj = [1]
        nenner = 1
        for m in range(n):
            if m==j: continue
            xm=xs[m]
            nenner=nenner*(xj-xm)
            Lj = Pmul(Lj, [-xm, 1])
        # Skaliere Lj mit yj / nenner
        Lj = [(c*yj)/ Fraction(nenner) for c in Lj]
        # Summiere auf
        if len(Lj)<len(coeffs): Lj=Lj+[0]*(len(coeffs)-len(Lj))
        if len(Lj)>len(coeffs): coeffs=coeffs+[0]*(-len(coeffs)+len(Lj))
        coeffs = [coeffs[i] + Lj[i] for i in range(len(coeffs))]
    for i in range(len(coeffs)):
        if type(coeffs[i])==Fraction and coeffs[i].denominator==1:
            coeffs[i]=coeffs[i].numerator
    return coeffs
xs=[1,2,3]; ys=[5,1,5]
p=InterPol(xs, ys)
print("Interpoly durch ",xs,ys," ist",Pstr(p))
for i in range(len(xs)):
    print("    p(",xs[i],")=",Pwert(p, xs[i]),"=",ys[i])

def teiler(n):
    if n>0: return [t for t in range(1,n+1) if n%t==0]
    if n<0: return [-t for t in range(1,-n+1) if (-n)%t==0]
def PFactor(p:list[int])->list[list]:
    if not isinstance(p, list) or not all(isinstance(x, int) for x in p):
        return []
    if len(p) == 0: return []
    if len(p) == 1: return [p]
    if p[0] == 0: # man kann x faktorisieren
        return [[0,1]] + PFactor(p[1:])
    def product(list_of_lists):
        if not list_of_lists: return [[]]
        rest = product(list_of_lists[1:])
        result = []
        for item in list_of_lists[0]:
            for r in rest: result.append([item] + r)
        return result
    n = len(p) - 1  # Grad
    for d in range(1, n):  # Mögliche Grade des Faktors
        xs = list(range(1, d+2))  # d+1 Werte
        ys = [Pwert(p, x) for x in xs]
        # Alle möglichen Kombinationen g(x_i) * h(x_i) = f(x_i)
        value_sets = [teiler(y) for y in ys]
        for gs in product(value_sets):  # Alle möglichen g(x_i)
            g_poly = InterPol(xs, gs)
            if Pdeg(g_poly)<1: continue
            if g_poly is None:
                continue
            # Teste, ob g_poly wirklich Teiler von p ist
            [q, r] =  Pdiv(p, g_poly)
            if r==[]:
                if q == g_poly:  # Wiederholung erkannt
                    return [g_poly, g_poly]
                else:
                    return [g_poly] + PFactor(q)
    return [p]  # irreduzibel
p=[1,3,3,1]
pf=PFactor(p)
print(Pstr(p)+" Faktoren : "+str([Pstr(f) for f in pf]))
p=[-5,-14,-7,-13,-2,1]
pf=PFactor(p)
print(Pstr(p)+" Faktoren : "+str([Pstr(f) for f in pf]))

Interpoly durch  [1, 2, 3] [5, 1, 5]  ist 4*x^2+-16*x+17
    p( 1 )= 5 = 5
    p( 2 )= 1 = 1
    p( 3 )= 5 = 5
1*x^3+3*x^2+3*x+1 Faktoren : ['+1*x+1', '+1*x+1', '+1*x+1']
1*x^5+-2*x^4+-13*x^3+-7*x^2+-14*x+-5 Faktoren : ['+1*x+-5', '1*x^2+1', '1*x^2+3*x+1']


In [19]:
import numpy as np
v = np.array([1, 2, 3])    # Vektor aus einer Liste
u = np.array([4, 5, 6])
print("u=",u,"v=",v)
print("u+v=",u+v)    # Vektoraddition
print("u-v=",u-v)    # Vektorsubtraktion
print("2*u=",2*u)    # Skalarmultiplikation
print("u*v=",u*v)    # komponentenweise Multiplikation
print("u.v=",np.dot(u,v)) # Skalarprodukt
print("uxv=",np.cross(u,v)) # Kreuzprodukt
print("|u|=",np.linalg.norm(u) ) # Länge
A = np.array([[1, 2, 0], 
              [3, 4, 7],
              [-2,3,0.5]])     # 3x3-Matrix
B = np.array([[0, 1, 0], 
              [1, 0, 1],
              [-1,0, 1]])     
print("A=",A,"B=",B)
print("A.v=",A@v) # Matrix-Vektor-Multiplikation
print("A.B=",A@B) # Matrix-Matrix-Multiplikation
print("det(A)=",np.linalg.det(A))
print("A.A^(-1)=",A@np.linalg.inv(A))
print("Eigenwerte und Eigenvektoren",list(np.linalg.eig(A)))

u= [4 5 6] v= [1 2 3]
u+v= [5 7 9]
u-v= [3 3 3]
2*u= [ 8 10 12]
u*v= [ 4 10 18]
u.v= 32
uxv= [ 3 -6  3]
|u|= 8.774964387392123
A= [[ 1.   2.   0. ]
 [ 3.   4.   7. ]
 [-2.   3.   0.5]] B= [[ 0  1  0]
 [ 1  0  1]
 [-1  0  1]]
A.v= [ 5.  32.   5.5]
A.B= [[ 2.   1.   2. ]
 [-3.   3.  11. ]
 [ 2.5 -2.   3.5]]
det(A)= -49.99999999999999
A.A^(-1)= [[ 1.00000000e+00 -1.38777878e-17 -5.55111512e-17]
 [-2.77555756e-16  1.00000000e+00 -3.46944695e-17]
 [-1.11022302e-16  5.55111512e-17  1.00000000e+00]]
Eigenwerte und Eigenvektoren [array([-3.69839983,  1.83636088,  7.36203894]), array([[ 0.29930443, -0.82032101,  0.28481796],
       [-0.70312594, -0.3430422 ,  0.90601147],
       [ 0.64500447,  0.45759751,  0.31308457]])]
